"""Add description and author fields to models

Revision ID: fd64b4ccb8be
Revises: 0eba3dcd5f93
Create Date: 2024-12-09 15:50:25.654204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd64b4ccb8be'
down_revision: Union[str, None] = '0eba3dcd5f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('author', sa.String(), nullable=True))
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('incomes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('incomes', sa.Column('author', sa.String(), nullable=True))
    op.alter_column('incomes', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incomes', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('incomes', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomes', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('incomes', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('incomes', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('incomes', 'author')
    op.drop_column('incomes', 'description')
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('expenses', 'author')
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###
